// ---- タグ定義ファイル ----
// ---- 背景画像リスト ----
// ここにファイル名（拡張子なし）を追加・削除するだけで反映されます
window.BgImages = [
  "white",
  "black",
  "classroom_front",
  "classroom_back",
  "harakubo_execution_hall",
  "waiting_room",
  "private_room",
  "you_are_cleric",
  "corridor",
  "blood_splatter",
  "warehouse",
  "entrance",
  "dining_room",
  "city_station_square",
  "stairs",
  "library",
  "reference_room",
  "entertainment_room",
  "school_warehouse",
  "mito_execution",
  "admin",
  "city",
  "school_gym",
  "school_gym_up",
  "sky",
  "school_entrance",
  "city_station_square",
  "hospital",
  "hall_above",
  "hall",
];

// ---- BGM リスト ----
// ここにファイル名（拡張子なし）を追加・削除するだけで反映されます
window.BgmList = [
  "mute",
  "quiet_ambient",
  "sanada_kazan_theme",
  "amari_anju_theme",
  "ichigin_fuga_theme",
  "mito_mito_theme",
  "roga_miki_theme",
  "extraordinary",
  "everyday_life_as_usual",
  "pessimism",
  "quiet_outside",
  "never_fade",
  "harakubo_yuiko_theme",
  "private",
  "karma",
  "pursuit",
  "tutorial_discussion",
  "discussion_common_upper",
  "karma_second",
  "my_memory",
  "discussion_connection",
  "discussion_more",
  "heartbeat",
  "noisy_outside",
  "survive_with_you",
  "ever",
  "regret",
  "alive",
  "showdown",
  "unacceptable_ending",
  "link_to_next",
];


