window.CharacterExpressions = window.CharacterExpressions || {};
window.CharacterExpressions.roga = [
  "normal/anger_talk",
  "normal/bear",
  "normal/bearish",
  "normal/cry",
  "normal/damaged",
  "normal/doubt",
  "normal/glare",
  "normal/guilty",
  "normal/guilty_talk",
  "normal/normal",
  "normal/puzzled",
  "normal/rage_talk",
  "normal/smile_talk",
  "normal/sneer",
  "normal/straight",
  "normal/surprise",
  "normal/talk",
  "normal/troubled_smile_talk",
  "normal/worry",
  "normal/upset_talk",
  "normal/bear_tear",
  "normal/unrest_serious_talk",
  "normal/tears_of_frustration_smile",
  "normal/tears_sneer",
];
